### ISSUE TITLE
Exception on Rotate gesture

### ISSUE THREAD

**Issue by ThexXTURBOXx** [JonasWanke/timetable#92]
**Describe the bug**

When doing a "rotate" gesture, `timetable` throws an exception.

**Videos**

https://www.youtube.com/watch?v=XXklEDTz8Xk

**Environment:**
- Device:  Emulator Pixel 4
- OS version:  Android 12 (SDK 31 Preview)
- Package version:  1.0.0-alpha3

<details>
<summary>The exception as reported by `catcher`</summary>

```
I/flutter ( 6983): [2021-08-03 10:16:05.260134 | Catcher | INFO] ---------- ERROR ----------
I/flutter ( 6983): [2021-08-03 10:16:05.262148 | Catcher | INFO] Unsupported operation: Infinity or NaN toInt
I/flutter ( 6983): [2021-08-03 10:16:05.262479 | Catcher | INFO] 
I/flutter ( 6983): [2021-08-03 10:16:05.262849 | Catcher | INFO] ------- STACK TRACE -------
I/flutter ( 6983): [2021-08-03 10:16:05.264172 | Catcher | INFO] #0      double.toInt (dart:core-patch/double.dart:219:36)
I/flutter ( 6983): [2021-08-03 10:16:05.264894 | Catcher | INFO] #1      double.round (dart:core-patch/double.dart:182:34)
I/flutter ( 6983): [2021-08-03 10:16:05.265414 | Catcher | INFO] #2      Duration.* (dart:core/duration.dart:164:56)
I/flutter ( 6983): [2021-08-03 10:16:05.266066 | Catcher | INFO] #3      _TimeZoomState._onScaleUpdate (package:timetable/src/time/zoom.dart:157:50)
I/flutter ( 6983): [2021-08-03 10:16:05.266620 | Catcher | INFO] #4      _ScaleGestureRecognizer._advanceStateMachine.<anonymous closure> (package:timetable/src/time/zoom.dart:626:18)
I/flutter ( 6983): [2021-08-03 10:16:05.267189 | Catcher | INFO] #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter ( 6983): [2021-08-03 10:16:05.267669 | Catcher | INFO] #6      _ScaleGestureRecognizer._advanceStateMachine (package:timetable/src/time/zoom.dart:625:7)
I/flutter ( 6983): [2021-08-03 10:16:05.267910 | Catcher | INFO] #7      _ScaleGestureRecognizer.handleEvent (package:timetable/src/time/zoom.dart:502:7)
I/flutter ( 6983): [2021-08-03 10:16:05.268762 | Catcher | INFO] #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
I/flutter ( 6983): [2021-08-03 10:16:05.269154 | Catcher | INFO] #9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
I/flutter ( 6983): [2021-08-03 10:16:05.269353 | Catcher | INFO] #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
I/flutter ( 6983): [2021-08-03 10:16:05.269484 | Catcher | INFO] #11     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
I/flutter ( 6983): [2021-08-03 10:16:05.270946 | Catcher | INFO] #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
I/flutter ( 6983): [2021-08-03 10:16:05.272237 | Catcher | INFO] #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
I/flutter ( 6983): [2021-08-03 10:16:05.272590 | Catcher | INFO] #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
I/flutter ( 6983): [2021-08-03 10:16:05.272833 | Catcher | INFO] #15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
I/flutter ( 6983): [2021-08-03 10:16:05.273364 | Catcher | INFO] #16     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
I/flutter ( 6983): [2021-08-03 10:16:05.274796 | Catcher | INFO] #17     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
I/flutter ( 6983): [2021-08-03 10:16:05.275866 | Catcher | INFO] #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
I/flutter ( 6983): [2021-08-03 10:16:05.276019 | Catcher | INFO] #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
I/flutter ( 6983): [2021-08-03 10:16:05.276720 | Catcher | INFO] #20     _rootRunUnary (dart:async/zone.dart:1370:13)
I/flutter ( 6983): [2021-08-03 10:16:05.276992 | Catcher | INFO] #21     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
I/flutter ( 6983): [2021-08-03 10:16:05.277250 | Catcher | INFO] #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
I/flutter ( 6983): [2021-08-03 10:16:05.277675 | Catcher | INFO] #23     _invoke1 (dart:ui/hooks.dart:182:10)
I/flutter ( 6983): [2021-08-03 10:16:05.278218 | Catcher | INFO] #24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
I/flutter ( 6983): [2021-08-03 10:16:05.278634 | Catcher | INFO] #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```
</details>

**Comment by JonasWanke** [comment]
This is now fixed as part of [v1.0.0-alpha.4](https://pub.dev/packages/timetable/versions/1.0.0-alpha.4/changelog#100-alpha4--2021-08-06)
